#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1
if [ -z "${destination}" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# Load configuration
payload=$(mktemp ${TMPDIR}/git-resource-request.XXXXXX)
cat > ${payload} <&0

GIT_RESOURCE_CONFIG=$(jq -r '{ source: .source.git }' < ${payload})

# Get the github repo
git_destination="$(mktemp -d -t git-resource-destination.XXXXXX)"
/opt/git-resource/in "${git_destination}" <<< "${GIT_RESOURCE_CONFIG}"

# Run composer install
cd "${git_destination}"
composer install --ignore-platform-reqs --no-interaction --optimize-autoloader

# Copy vendor to the destination
mv vendor "${git_destination}/vendor/"
